name: Build on push

on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Inject signing key
        run: |
          echo '${{ secrets.KEY_STORE }}' | base64 --decode > ${{ github.workspace }}/keystore.jks
      - name: Build with Gradle
        run: |
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          echo 'android.native.buildOutput=verbose' >> gradle.properties
          ./gradlew assembleFossDebug \
          -Pandroid.injected.signing.store.file=${{ github.workspace }}/keystore.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.RELEASE_STORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.RELEASE_KEY_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.RELEASE_KEY_PASSWORD }}
      - name: Upload built apk
        if: success()
        uses: actions/upload-artifact@v3
        with:
          path: |
            ${{ github.workspace }}/app/build/outputs/apk/foss/debug/*.apk
